apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-controller
spec:
  roles:
    - os:admin