apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - talos-cluster-operator.lukaspj.com
    resources:
      - clusters
      - machines
  - verbs:
      - '*'
    apiGroups:
      - talos-cluster-operator.lukaspj.com
    resources:
      - clusters
      - machines
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch

