apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-server
---
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-server
spec:
  roles:
    - os:admin